
load("//deps/toolchain:get.bzl", "toolchain")
load("//deps/bazel_skylib:get.bzl", "bazelSkylib")
load("//deps/aspect_bazel_lib:get.bzl", "aspectBazelLib")
load("//deps/type_safe:get.bzl", "typeSafe")
load("//deps/cppast:get.bzl", "cppast")

toolchain()
bazelSkylib()
aspectBazelLib()
typeSafe()
cppast()


# Pull in a hermetic clang toolchain.  This is where we will also source libclang for cppast.
load("@com_grail_bazel_toolchain//toolchain:deps.bzl", "bazel_toolchain_dependencies")

bazel_toolchain_dependencies()

load("@com_grail_bazel_toolchain//toolchain:rules.bzl", "llvm_toolchain")

llvm_toolchain(
    name = "llvm_toolchain",
    llvm_version = "11.0.0",
)

load("@llvm_toolchain//:toolchains.bzl", "llvm_register_toolchains")

llvm_register_toolchains()