name: CI
on: [push, pull_request]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.on }}
    strategy:
      matrix:
        on:
          ubuntu-24.04
          macos-15
          macos-15-intel

    steps:
    - uses: actions/checkout@v5
      with: { submodules: recursive }
    - uses: prefix-dev/setup-pixi@v0.9.4
      with: { pixi-version: v0.68.0 }
    - name: run tests
      run: pixi run test
